### ISSUE TITLE
Link is broken generated by `DescriptionRenderer` ?

### ISSUE THREAD

**Issue by ydah** [r7kamura/rubocop_todo_corrector#12]
The links generated by the `DescriptionRenderer` appear to be broken.
(Maybe it is just not visible at the moment.)

https://github.com/r7kamura/rubocop_todo_corrector/blob/98868caff82d246b0275bc7d1664722ff1ce5a63/lib/rubocop_todo_corrector/description_renderer.rb#L47

For example [Style/StringLiterals](https://docs.rubocop.org/rubocop/cops_style.html#stylestringliterals) .
The following URL is generated, but the transition destination does not seem to exist.

https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/StringLiterals

![screen shot](https://user-images.githubusercontent.com/13041216/182290459-525888c5-6890-4cc1-b8e1-8acb3acdac72.png)

**Comment by r7kamura** [comment]
Maybe rubydoc's issue? 

The page exists on 1.31.2, but it doesn't on 1.32.0.

- https://www.rubydoc.info/gems/rubocop/1.32.0/RuboCop/Cop/Style/StringLiterals
- https://www.rubydoc.info/gems/rubocop/1.31.2/RuboCop/Cop/Style/StringLiterals

How do you think we should deal with this?

**Comment by r7kamura** [comment]
I came to this conclusion because the sidebar of RuboCop page shows almost nothing.

![image](https://user-images.githubusercontent.com/111689/182293886-9eb32ef1-a6e5-4e91-93b5-2f8c626a07e5.png)


- https://www.rubydoc.info/gems/rubocop

It usually displays a list of classes, etc.

**Comment by ydah** [comment]
I see, that's true. I think I will close this Issue itself. Thanks for checking.
It seems likely that documentation is not being generated due to build errors when cutting a new release version.
